name: PowerLevel
version: 1.10.0
description: Makes players more powerful when they hold onto their levels instead of spending them.
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-powerlevel/
main: com.moltendorf.bukkit.powerlevel.Plugin
